---
title: "berries"
author: "MA615"
date: "10/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(magrittr)
library(kableExtra)
```



```{r}
## read the data

ag_data <- read_csv("berries.csv", col_names = TRUE)

## look at number of unique values in each column
ag_data %>% summarize_all(n_distinct) -> aa


## make a list of the columns with only one unique value
bb <- which(aa[1,]==1)

## list the 1-unique valu column names 
cn <- colnames(ag_data)[bb]

```



```{r}
## remove the 1-unique columns from the dataset
ag_data %<>% select(-all_of(bb))

aa %<>% select(-all_of(bb)) 


## State name and the State ANSI code are (sort of) redundant
## Just keep the name
ag_data %<>% select(-4)
aa %<>% select(-4) 


kable(head(ag_data)) %>% kable_styling(font_size=12)

```

```{r}
berry <- unique(ag_data$Commodity)
nberry <- length(berry)
```

```{r}
rberry <- ag_data %>% filter((Commodity=="RASPBERRIES") & (Period=="YEAR"))
rberry %<>% select(-c(Period, Commodity))   

#### Does every Data Item begin with "
sum(str_detect(rberry$`Data Item`, "^RASPBERRIES, ")) == length(rberry$`Data Item`)


rberry %<>% separate(`Data Item`, c("B","type", "meas", "what"), sep = ",") 
rberry %<>% select(-B)


rberry %<>% separate(type,c("b1", "type", "b2", "lab1", "lab2"), " ")

rberry %<>% select(-c(b1,b2)) 

rberry[is.na(rberry)] <- " "  ## OK now Data Item has been split into parts

```

```{r}
rberry %<>% separate(Domain, c("D_left", "D_right"), sep = ", ")

rberry[is.na(rberry)] <- " "

## And now Domain Category


rberry %<>% separate(`Domain Category`, c("DC_left", "DC_right"), sep = ", ")

## looks like DC_left combines labels

head(rberry$DC_left %>% unique(),n=20)
head(rberry$DC_right %>% unique(), n=20)


## work on DC_left first

rberry %<>% separate(DC_left, c("DC_left_l", "DC_left_r"), sep = ": ")

## bberry$DC_left_l %>% unique()
## bberry$DC_left_r %>% unique()

## now work on DC_right

head(rberry$DC_right %>% unique(), n=20)

rberry %<>% separate(DC_right, c("DC_right_l", "DC_right_r"), sep = ": ") 


rberry[is.na(rberry)] <- " "

##  OK now we need to eliminate the redundancy
```
# eliminate redundancy in pesticide columns
```{r}
# eliminate redundancy in pesticide columns

rberry %<>% mutate(pesticide = ifelse(rberry$D_right==rberry$DC_right_l, rberry$D_right, NA))
#sum(is.na(rberry$pesticide))

rberry %<>% select(-c(D_right, DC_right_l))

rberry %<>% mutate(pesticide_type = ifelse(rberry$D_left==rberry$DC_left_l, rberry$D_left, NA))
which(is.na(rberry$pesticide_type))

rberry %<>% select(-c(D_left, DC_left_l))

rberry[is.na(rberry)] <- " "
```

```{r}
# combine DC_left_r and DC_right_r columns into a new column "chemicals"
rberry$chemicals <- paste(rberry$DC_left_r, rberry$DC_right_r, sep = "")

rberry %<>% select(-c(DC_left_r, DC_right_r))
```

```{r}
# remove "/" in lab2 column
unique(rberry$lab2)
rberry$lab2 <- ifelse(rberry$lab2=="/", NA, rberry$lab2)

rberry[is.na(rberry)] <- " "
```

```{r}
# remove "-" in lab1 column
unique(rberry$lab1)
rberry$lab1 <- ifelse(rberry$lab1=="-", NA, rberry$lab1)

rberry[is.na(rberry)] <- " "
```
```{r}
# combine lab1 and lab2 columns

rberry$label <- paste(rberry$lab1, rberry$lab2, sep = "")

rberry$label <- ifelse(rberry$label=="ACRESHARVESTED", "ACRES HARVESTED", rberry$label)

unique(rberry$label)

rberry %<>% select(-c(lab1, lab2))
```

```{r}
unique(rberry$meas)
```

